export const videos = {
	data: [
		{
			title: 'Nutrição 101: Fundamentos de uma Dieta Saudável',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/assets_163.png'),
			video_source: require('@/assets/Audio/saude.mp4'),
			category_name: 'Nutrição',
		},
		{
			title:
				'Tudo o Você Precisa Saber Antes de Cursar Nutrição | Será que é Para Você?',
			category_name: 'Nutrição',
			video_source: require('@/assets/Audio/1080p.mp4'),
			imageUri: require('@/assets/Thumbnails/assets_164.png'),
			duration: '30 minutos',
		},
		{
			title: 'Descubra os Benefícios da Meditação Diária para a Saúde Mental',
			duration: '15 minutos',
			imageUri: require('@/assets/Thumbnails/assets_165.png'),
			video_source: require('@/assets/Audio/big_buck_bunny.mp4'),
			category_name: 'Nutrição',
		},
		{
			title: 'As Melhores Receitas para uma Alimentação Saudável no Dia a Dia',
			duration: '40 minutos',
			imageUri: require('@/assets/Thumbnails/9v1t92ym.png'),
			video_source: require('@/assets/Audio/14129.mp4'),
			category_name: 'Saude',
		},
		{
			title: 'Agricultura: Sistemas agrícolas e modos de produção',
			duration: '40 minutos',
			imageUri: require('@/assets/Thumbnails/xnfxrniu.png'),
			video_source: require('@/assets/Audio/2160p.mp4'),
			category_name: 'Agricultura',
		},
		{
			title: 'Agricultura: como produzir tabaco',
			duration: '20 minutos',
			imageUri: require('@/assets/Thumbnails/5t18qb1m.png'),
			video_source: require('@/assets/Audio/pexels-marta.mp4'),
			category_name: 'Agricultura',
		},
		{
			title: 'A Importância da Higiene: Cuidados Diários',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/higiene.jpg'),
			video_source: require('@/assets/Audio/pexels-marta.mp4'),
			category_name: 'Higiene',
		},
		{
			title: 'Dicas de Higiene Pessoal para uma Vida Saudável',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/higiene-2.jpg'),
			video_source: require('@/assets/Audio/1080p.mp4'),
			category_name: 'Higiene',
		},

		{
			title: 'Ouro Negro: Episódio 1',
			duration: '23 minutos',
			imageUri: require('@/assets/Thumbnails/Retângulo_499.png'),
			video_source: require('@/assets/Audio/Lion.mp3'),
			category_name: '',
			category_id: 1,
		},
		{
			title: 'Ouro Negro: Episódio 2',
			duration: '25 minutos',
			imageUri: require('@/assets/Thumbnails/Retângulo_499.png'),
			video_source: require('@/assets/Audio/happ.mp3'),
			category_id: 1,
		},
		{
			title: 'Ouro Negro: Episódio 3',
			duration: '40 minutos',
			imageUri: require('@/assets/Thumbnails/Retângulo_499.png'),
			video_source: require('@/assets/Audio/Hello.mp3'),
			category_id: 1,
		},

		{
			title: 'À Porta Da Minha Casa',
			duration: '7 segundos',
			imageUri: require('@/assets/Thumbnails/Retângulo_499.png'),
			video_source: require('@/assets/Audio/Dog.mp3'),
			category_name: '',
			category_id: 3,
		},

		{
			title: 'Janete - Episodio 1',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/janete.png'),
			video_source: require('@/assets/Audio/audio.mp3'),
			category_name: '',
			category_id: 10,
		},
		{
			title: 'Janete - Episodio 2',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/janete.png'),
			video_source: require('@/assets/Audio/Hello.mp3'),
			category_name: '',
			category_id: 10,
		},
		{
			title: 'Janete - Episodio 3',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/janete.png'),
			video_source: require('@/assets/Audio/Birds.mp3'),
			category_name: '',
			category_id: 10,
		},

		{
			title: 'Kuga Munu - Episodio 1',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/hugo.png'),
			video_source: require('@/assets/Audio/ep3.mp4'),
			category_name: '',
			category_id: 5,
		},
		{
			title: 'Maida',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/maida.png'),
			video_source: require('@/assets/Audio/ep4.mp4'),
			category_name: '',
			category_id: 4,
		},
		{
			title: 'Kuga Munu - Episodio 2',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/hugo.png'),
			video_source: require('@/assets/Audio/ep2.mp4'),
			category_name: '',
			category_id: 5,
		},

		{
			title: 'Aquele papo - trailer',
			duration: '12 minutos',
			imageUri: require('@/assets/Thumbnails/Retângulo_502.png'),
			video_source: require('@/assets/Audio/aquele_papo1.mp4'),
			category_name: '',
			category_id: 6,
		},
	],
}
